export const DEFAULT_STATE = {
  meta: {
    version: 1,
    title: "Pulycort - visor 3D instalaciones",
    sourceImage: "public/assets/plano-google-maps-pulycort.png",
    sourceNotes:
      "Base aproximada a partir de captura Google Maps y catalogo documentado de maquinas. Validar ubicaciones en visita.",
    mapCalibration: {
      version: 3,
      x: 2,
      z: 16,
      width: 200,
      depth: 125,
      rotation: -17,
      opacity: 0.72,
    },
    layoutVersion: 2,
  },
  areas: [
    {
      id: "area-nave-principal",
      name: "Nave principal",
      use: "Telar, reforzado y flujo de tabla",
      type: "edificio",
      x: -21,
      z: -6,
      width: 60,
      depth: 19,
      height: 4.8,
      rotation: -6,
      color: "#aeb8b7",
      notes: "Huella aproximada de la cubierta central superior.",
    },
    {
      id: "area-nave-central",
      name: "Nave central",
      use: "Pulido, disco puente y paso a losa",
      type: "edificio",
      x: 2,
      z: 19,
      width: 55,
      depth: 18,
      height: 4.4,
      rotation: -5,
      color: "#bac2bd",
      notes: "Pendiente de confirmar maquinaria exacta dentro de la nave.",
    },
    {
      id: "area-nave-solar",
      name: "Nave solar sur",
      use: "Almacen cubierto / apoyo logistico",
      type: "edificio",
      x: 39,
      z: 30,
      width: 24,
      depth: 39,
      height: 5,
      rotation: -4,
      color: "#9fb0ad",
      notes: "Cubierta con paneles solares visibles en la captura.",
    },
    {
      id: "area-entrada-oficinas",
      name: "Entrada y oficinas",
      use: "Acceso, oficinas y recepcion",
      type: "servicio",
      x: 48,
      z: 3,
      width: 26,
      depth: 22,
      height: 3.5,
      rotation: 18,
      color: "#c88a61",
      notes: "Zona de acceso y edificios auxiliares.",
    },
    {
      id: "area-carga-este",
      name: "Campas este",
      use: "Carga, descarga y stock exterior",
      type: "patio",
      x: 64,
      z: -17,
      width: 31,
      depth: 24,
      height: 0.16,
      rotation: 10,
      color: "#c7b99b",
      notes: "Patio amplio junto al acceso desde CV-840.",
    },
    {
      id: "area-patio-bloques-oeste",
      name: "Patio bloques oeste",
      use: "Bloques y material bruto",
      type: "patio",
      x: -52,
      z: 8,
      width: 43,
      depth: 32,
      height: 0.16,
      rotation: -5,
      color: "#bca776",
      notes: "Zona exterior con acumulacion de bloques en la captura.",
    },
    {
      id: "area-tablas-norte",
      name: "Stock tablas norte",
      use: "Tablas y caballetes",
      type: "patio",
      x: 18,
      z: -18,
      width: 45,
      depth: 18,
      height: 0.16,
      rotation: -2,
      color: "#b8b1a0",
      notes: "Zona exterior junto a la carretera.",
    },
    {
      id: "area-patio-sur",
      name: "Patio sur",
      use: "Palets, tablas y preparacion",
      type: "patio",
      x: -4,
      z: 38,
      width: 70,
      depth: 16,
      height: 0.16,
      rotation: -8,
      color: "#c4b78f",
      notes: "Patio longitudinal bajo la nave central.",
    },
    {
      id: "area-carretera",
      name: "CV-840 / acceso",
      use: "Referencia exterior",
      type: "referencia",
      x: 20,
      z: -44,
      width: 116,
      depth: 6,
      height: 0.08,
      rotation: -2,
      color: "#6f7680",
      notes: "Referencia visual para orientarse en el plano.",
    },
  ],
  machines: [
    {
      id: "maq-reforzadora-bloques",
      code: "1",
      name: "REFORZADORA BLOQUES",
      category: "Reforzado",
      unit: "M3",
      areaId: "area-nave-principal",
      status: "Pendiente validar ubicacion",
      x: -24,
      z: -8,
      rotation: -6,
      services: ["REFORZADO BLOQUE"],
      assignedTo: "",
      notes: "Catalogo documentado. Ubicacion inicial aproximada.",
    },
    {
      id: "maq-monohilo",
      code: "2",
      name: "MONOHILO",
      category: "Corte hilo",
      unit: "M3",
      areaId: "area-patio-bloques-oeste",
      status: "Pendiente validar ubicacion",
      x: -35,
      z: 5,
      rotation: -10,
      services: ["CORTE DE HILO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-telar-1",
      code: "3",
      name: "TELAR 1",
      category: "Telar",
      unit: "M3",
      areaId: "area-nave-principal",
      status: "Pendiente validar ubicacion",
      x: -12,
      z: -11,
      rotation: -6,
      services: ["ASERRADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-telar-2",
      code: "4",
      name: "TELAR 2",
      category: "Telar",
      unit: "M3",
      areaId: "area-nave-principal",
      status: "Pendiente validar ubicacion",
      x: -5,
      z: -11,
      rotation: -6,
      services: ["ASERRADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-telar-3",
      code: "5",
      name: "TELAR 3",
      category: "Telar",
      unit: "M3",
      areaId: "area-nave-principal",
      status: "Pendiente validar ubicacion",
      x: 2,
      z: -11,
      rotation: -6,
      services: ["ASERRADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-telar-4",
      code: "6",
      name: "TELAR 4",
      category: "Telar",
      unit: "M3",
      areaId: "area-nave-principal",
      status: "Pendiente validar ubicacion",
      x: 9,
      z: -11,
      rotation: -6,
      services: ["ASERRADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-telar-externo",
      code: "7",
      name: "TELAR EXTERNO",
      category: "Telar",
      unit: "M3",
      areaId: "area-tablas-norte",
      status: "Referencia externa",
      x: 7,
      z: -28,
      rotation: -2,
      services: ["ASERRADO"],
      assignedTo: "",
      notes: "Elemento de referencia; confirmar si debe representarse dentro de planta.",
    },
    {
      id: "maq-cortabloques",
      code: "8",
      name: "CORTABLOQUES",
      category: "Corte bloque",
      unit: "M2",
      areaId: "area-patio-bloques-oeste",
      status: "Pendiente validar ubicacion",
      x: -42,
      z: 17,
      rotation: -8,
      services: ["CORTABLOQUE", "DESPUNTAR EN CORTABLOQUES"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-reforzadora-1",
      code: "9",
      name: "REFORZADORA 1",
      category: "Reforzado tabla",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: -8,
      z: 17,
      rotation: -5,
      services: ["FILTRADO EPOXI", "FILTRADO POLIESTER", "REFORZADO EPOXI", "REFORZADO POLIESTER", "MASILLADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-reforzadora-2-sei",
      code: "10",
      name: "REFORZADORA 2 SEI",
      category: "Reforzado tabla",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: 1,
      z: 17,
      rotation: -5,
      services: ["FILTRADO EPOXI", "FILTRADO POLIESTER", "REFORZADO EPOXI", "REFORZADO POLIESTER"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-pulidora-tabla-simec",
      code: "11",
      name: "PULIDORA TABLA SIMEC",
      category: "Pulido tabla",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: 12,
      z: 17,
      rotation: -5,
      services: ["PULIDO", "APOMAZADO", "ARENADO", "ENVEJECIDO", "LEATHER", "HORAS TRABAJO"],
      assignedTo: "",
      notes: "Servicios resumidos para MVP; ver fuente para listado completo.",
    },
    {
      id: "maq-discopuente-1-terzago",
      code: "12",
      name: "DISCOPUENTE 1 TERZAGO",
      category: "Disco puente",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: 20,
      z: 17,
      rotation: -5,
      services: ["CORTE DISCO PUENTE", "HORAS TRABAJO", "SCRATCH / RAYADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-discopuente-2-gomez",
      code: "13",
      name: "DISCOPUENTE 2 GOMEZ",
      category: "Disco puente",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: 28,
      z: 17,
      rotation: -5,
      services: ["CORTE DISCO PUENTE", "HORAS TRABAJO", "SCRATCH / RAYADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-discopuente-3-canigo",
      code: "14",
      name: "DISCOPUENTE 3 CANIGO",
      category: "Disco puente",
      unit: "M2",
      areaId: "area-nave-central",
      status: "Pendiente validar ubicacion",
      x: 36,
      z: 17,
      rotation: -5,
      services: ["CORTE DISCO PUENTE", "HORAS TRABAJO", "SCRATCH / RAYADO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-control-numerico-donatoni",
      code: "15",
      name: "CONTROL NUMERICO DONATONI",
      category: "Control numerico",
      unit: "M2",
      areaId: "area-nave-solar",
      status: "Pendiente validar ubicacion",
      x: 28,
      z: 30,
      rotation: -4,
      services: ["CORTE DISCO PUENTE", "HORAS TRABAJO"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-pulidora-losa",
      code: "16",
      name: "PULIDORA LOSA",
      category: "Pulido losa",
      unit: "M2",
      areaId: "area-nave-solar",
      status: "Pendiente validar ubicacion",
      x: 34,
      z: 39,
      rotation: -4,
      services: ["PULIDO", "APOMAZADO", "ARENADO", "ENVEJECIDO", "LEATHER", "PERFILADO", "HORAS TRABAJO"],
      assignedTo: "",
      notes: "Del disco puente salen losas a palet y pasan a pulidora de losas segun cuestionario.",
    },
    {
      id: "maq-biseladora",
      code: "17",
      name: "BISELADORA",
      category: "Acabado canto",
      unit: "M2",
      areaId: "area-nave-solar",
      status: "Pendiente validar ubicacion",
      x: 43,
      z: 36,
      rotation: -4,
      services: ["BISELADO", "CLASIFICAR"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-recuperadora",
      code: "18",
      name: "RECUPERADORA",
      category: "Recuperacion",
      unit: "M2",
      areaId: "area-patio-sur",
      status: "Pendiente validar ubicacion",
      x: -13,
      z: 38,
      rotation: -8,
      services: ["CORTE RECUPERADORA"],
      assignedTo: "",
      notes: "",
    },
    {
      id: "maq-taller",
      code: "19",
      name: "TALLER",
      category: "Taller",
      unit: "M2",
      areaId: "area-entrada-oficinas",
      status: "Pendiente validar ubicacion",
      x: 51,
      z: 6,
      rotation: 18,
      services: ["CANTO PULIDO", "BISELADO", "EMBALADO", "CORTE", "HORAS TRABAJO"],
      assignedTo: "",
      notes: "Servicios resumidos para MVP; ver fuente para listado completo.",
    },
  ],
  people: [
    {
      id: "per-responsable-planta",
      name: "Responsable planta",
      role: "Coordinacion produccion",
      shift: "Manana",
      areaId: "area-nave-principal",
      status: "Por asignar persona real",
      x: -18,
      z: -1,
      notes: "Alta de ejemplo para preparar la visita.",
    },
    {
      id: "per-operario-telar",
      name: "Operario telar",
      role: "Maquinista telar",
      shift: "Manana",
      areaId: "area-nave-principal",
      status: "Por asignar persona real",
      x: -5,
      z: -4,
      notes: "",
    },
    {
      id: "per-operario-pulidora",
      name: "Operario pulidora",
      role: "Acabados / pulido",
      shift: "Tarde",
      areaId: "area-nave-solar",
      status: "Por asignar persona real",
      x: 38,
      z: 31,
      notes: "",
    },
  ],
};
